version: '3.9'
services:
  app:
    image: node:16-slim
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 3000:3000
    command: bash -c "yarn install && yarn start:dev"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
